steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cloudeng-repo/health-dashboard:$COMMIT_SHA'
      - './app'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cloudeng-repo/health-dashboard:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i -e "s|__PROJECT_ID__|$PROJECT_ID|g" \
               -e "s|__IMAGE_TAG__|$COMMIT_SHA|g" \
               k8s/deployment.yaml
        grep image: k8s/deployment.yaml

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials cloudeng-cluster \
          --zone europe-west2-a --project $PROJECT_ID
        kubectl apply -f k8s/
        kubectl rollout status deployment/health-dashboard --timeout=180s

timeout: '900s'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cloudeng-repo/health-dashboard:$COMMIT_SHA'
  